# Generated by Django 4.0.2 on 2022-04-29 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_direccion_created_direccion_modified_empresa_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
