# Generated by Django 4.0.2 on 2022-04-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagen_alter_direccion_id_alter_empresa_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ManyToManyField(to='home.Imagen'),
        ),
    ]
