# Generated by Django 4.0.2 on 2022-05-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_empresa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
