# Generated by Django 4.0.2 on 2022-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_producto_imagen_imagen_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(max_length=10),
        ),
    ]
