# Generated by Django 4.0.2 on 2022-05-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_empresa_user_alter_producto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
