# Generated by Django 4.0.2 on 2022-06-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.empresa'),
        ),
    ]
