# Generated by Django 4.0.2 on 2022-06-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_reservacion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.empresa'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='folio',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='producto',
            field=models.ManyToManyField(blank=True, to='home.Producto'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('producto', models.ManyToManyField(blank=True, to='home.Producto')),
            ],
        ),
    ]
