# Generated by Django 4.0.2 on 2022-06-04 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_reservacion_empresa_alter_reservacion_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.empresa'),
        ),
    ]
