# Generated by Django 4.0.2 on 2022-06-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_paquete_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paquete',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
