# Generated by Django 4.0.2 on 2022-06-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_paquete_fecha_fin_paquete_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='home.tipo_producto'),
        ),
    ]
